# Generated by Django 6.0.4 on 2026-04-12 04:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('fornecedor_principal', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=14, null=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nivel', models.IntegerField(default=1)),
                ('permite_tintometria', models.BooleanField(default=False)),
                ('exige_formula', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventory.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nivel', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade_reservada', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('corredor', models.CharField(blank=True, max_length=20, null=True)),
                ('prateleira', models.CharField(blank=True, max_length=20, null=True)),
                ('data_ultima_movimentacao', models.DateTimeField(blank=True, null=True)),
                ('bloqueado_venda', models.BooleanField(default=False)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=200, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.loja')),
            ],
            options={
                'verbose_name': 'Estoque da Loja',
                'verbose_name_plural': 'Estoques das Lojas',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferência'), ('PERDA', 'Perda'), ('PRODUCAO', 'Produção')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('estoque_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventory.estoqueloja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoBase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_produto', models.CharField(choices=[('SIMPLES', 'Produto Simples'), ('COMPOSTO', 'Tinta Manipulada'), ('INSUMO', 'Pigmento/Base'), ('KIT', 'Kit de Produtos')], max_length=20)),
                ('especificacoes_tecnicas', models.JSONField(default=dict)),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='fichas_tecnicas/')),
                ('base_tintometrica', models.CharField(blank=True, max_length=50, null=True)),
                ('linha_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.marca')),
            ],
            options={
                'verbose_name': 'Produto Base',
                'verbose_name_plural': 'Produtos Base',
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_variacao', models.CharField(max_length=50)),
                ('nome_variacao', models.CharField(max_length=200)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
                ('cor_codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('fator_conversao_venda', models.DecimalField(decimal_places=4, default=1, help_text='Quantas unidades de estoque equivalem a 1 unidade de venda', max_digits=10)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('cest', models.CharField(blank=True, max_length=10, null=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_base', models.TextField(blank=True, null=True)),
                ('rendimento_por_litro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/variacoes/')),
                ('ativo', models.BooleanField(default=True)),
                ('produto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='inventory.produtobase')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produto',
            },
        ),
        migrations.AddField(
            model_name='estoqueloja',
            name='produto_variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produtovariacao'),
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('volume', 'Volume'), ('peso', 'Peso'), ('unidade', 'Unidade'), ('metro', 'Metro'), ('area', 'Área')], max_length=20)),
                ('fator_conversao', models.DecimalField(decimal_places=6, default=1, help_text='Fator para converter para a unidade base', max_digits=12)),
                ('unidade_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='inventory.unidademedida')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='unidade_estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_estoque', to='inventory.unidademedida'),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='unidade_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_venda', to='inventory.unidademedida'),
        ),
        migrations.AlterUniqueTogether(
            name='estoqueloja',
            unique_together={('loja', 'produto_variacao')},
        ),
        migrations.AlterUniqueTogether(
            name='produtovariacao',
            unique_together={('produto_base', 'codigo_variacao')},
        ),
    ]
