# Generated by Django 6.0.4 on 2026-04-13 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0002_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquereserva',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.venda'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='nfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscal.notafiscaleletronica'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.estoquereserva'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.venda'),
        ),
        migrations.AddField(
            model_name='produtobase',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.categoria'),
        ),
        migrations.AddField(
            model_name='produtobase',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.marca'),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='produto_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='inventory.produtobase'),
        ),
        migrations.AddField(
            model_name='produtounidade',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produtovariacao'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produtovariacao'),
        ),
        migrations.AddField(
            model_name='estoquereserva',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produtovariacao'),
        ),
        migrations.AddField(
            model_name='estoqueloja',
            name='produto_variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produtovariacao'),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='unidade_estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_estoque', to='inventory.unidademedida'),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='unidade_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_venda', to='inventory.unidademedida'),
        ),
        migrations.AddField(
            model_name='produtounidade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unidademedida'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='unidade_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_base', to='inventory.unidademedida'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='unidade_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='inventory.unidademedida'),
        ),
        migrations.AddField(
            model_name='estoquereserva',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unidademedida'),
        ),
        migrations.AlterUniqueTogether(
            name='estoqueloja',
            unique_together={('loja', 'produto_variacao')},
        ),
        migrations.AlterUniqueTogether(
            name='produtovariacao',
            unique_together={('produto_base', 'codigo_variacao')},
        ),
        migrations.AlterUniqueTogether(
            name='produtounidade',
            unique_together={('produto', 'unidade')},
        ),
    ]
