# Generated by Django 6.0.4 on 2026-04-13 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercadoria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_entrada', models.CharField(choices=[('COMPRA', 'Compra de Fornecedor'), ('TRANSFERENCIA', 'Transferência entre Lojas'), ('AJUSTE', 'Ajuste Positivo'), ('DEVOLUCAO', 'Devolução de Cliente'), ('BONIFICACAO', 'Bonificação')], default='COMPRA', max_length=20)),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('fornecedor_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('chave_acesso_nfe', models.CharField(blank=True, help_text='Chave de acesso de 44 dígitos da NF-e do fornecedor', max_length=44, null=True, unique=True)),
                ('numero_nfe', models.CharField(blank=True, max_length=9, null=True)),
                ('serie_nfe', models.CharField(blank=True, max_length=3, null=True)),
                ('data_emissao_nfe', models.DateField(blank=True, null=True)),
                ('xml_nfe', models.TextField(blank=True, null=True)),
                ('data_entrada', models.DateField()),
                ('data_conferencia', models.DateTimeField(blank=True, null=True)),
                ('valor_total_nfe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de Conferência'), ('CONFIRMADA', 'Confirmada'), ('ERRO', 'Erro no Processamento'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_mercadoria', to='companies.loja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Mercadoria',
                'verbose_name_plural': 'Entradas de Mercadoria',
                'ordering': ['-data_entrada', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoteProduto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=50)),
                ('codigo_barras_lote', models.CharField(blank=True, max_length=100, null=True)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField()),
                ('quantidade_inicial', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantidade_atual', models.DecimalField(decimal_places=4, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('VENCIDO', 'Vencido'), ('ESGOTADO', 'Esgotado'), ('BLOQUEADO', 'Bloqueado'), ('QUARENTENA', 'Em Quarentena')], default='ATIVO', max_length=15)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=200, null=True)),
                ('documento_entrada', models.CharField(blank=True, help_text='Chave de acesso da NF-e do fornecedor ou número do documento', max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='companies.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventory.produtovariacao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unidademedida')),
            ],
            options={
                'verbose_name': 'Lote de Produto',
                'verbose_name_plural': 'Lotes de Produto',
                'ordering': ['data_validade', 'data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='EntradaMercadoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao_nfe', models.CharField(max_length=200)),
                ('codigo_nfe', models.CharField(blank=True, max_length=60, null=True)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('cfop', models.CharField(blank=True, max_length=4, null=True)),
                ('cean', models.CharField(blank=True, max_length=14, null=True)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidade_nfe', models.CharField(blank=True, max_length=6, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Vinculação'), ('VINCULADO', 'Produto Vinculado'), ('PROCESSADO', 'Estoque Atualizado'), ('IGNORADO', 'Ignorado')], default='PENDENTE', max_length=15)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventory.entradamercadoria')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.produtovariacao')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unidademedida')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.loteproduto')),
            ],
            options={
                'verbose_name': 'Item de Entrada',
                'verbose_name_plural': 'Itens de Entrada',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='entradamercadoria',
            index=models.Index(fields=['loja', 'status'], name='inventory_e_loja_id_2f0ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='entradamercadoria',
            index=models.Index(fields=['chave_acesso_nfe'], name='inventory_e_chave_a_42c0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproduto',
            index=models.Index(fields=['produto', 'loja', 'status'], name='inventory_l_produto_2ef399_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproduto',
            index=models.Index(fields=['data_validade'], name='inventory_l_data_va_f9658a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loteproduto',
            unique_together={('produto', 'loja', 'numero_lote')},
        ),
    ]
