# Generated by Django 6.0.4 on 2026-04-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_lote_validade_entrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="entradamercadoria",
            name="origem_entrada",
            field=models.CharField(
                choices=[
                    ("XML_UPLOAD", "Upload de XML"),
                    ("MANUAL", "Entrada Manual"),
                    ("SEFAZ_DOWNLOAD", "Download SEFAZ"),
                ],
                default="XML_UPLOAD",
                help_text="Como esta entrada foi criada no sistema",
                max_length=20,
            ),
        ),
    ]
