# Generated by Django 6.0.4 on 2026-04-13 00:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(choices=[('DATABASE', 'Database'), ('REDIS', 'Redis Cache'), ('API', 'API Services'), ('CELERY', 'Background Tasks'), ('DISK', 'Disk Storage'), ('MEMORY', 'Memory Usage'), ('CPU', 'CPU Usage'), ('EXTERNAL_API', 'External APIs')], help_text='System component being monitored', max_length=50)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('DOWN', 'Down')], help_text='Current health status', max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('disk_usage', models.FloatField(blank=True, help_text='Disk usage percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('active_connections', models.IntegerField(blank=True, help_text='Number of active connections', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('queue_size', models.IntegerField(blank=True, help_text='Queue size for background tasks', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('error_count', models.IntegerField(default=0, help_text='Number of errors in this check interval', validators=[django.core.validators.MinValueValidator(0)])),
                ('error_message', models.TextField(blank=True, help_text='Last error message if any', null=True)),
                ('check_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this health check was performed')),
                ('additional_data', models.JSONField(blank=True, help_text='Additional metrics and metadata', null=True)),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['-check_timestamp'],
                'indexes': [models.Index(fields=['component', 'check_timestamp'], name='monitoring__compone_98baf1_idx'), models.Index(fields=['status', 'check_timestamp'], name='monitoring__status_70351f_idx'), models.Index(fields=['check_timestamp'], name='monitoring__check_t_cd55ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Brief alert title', max_length=200)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('alert_type', models.CharField(choices=[('SYSTEM_HEALTH', 'System Health'), ('BACKUP_FAILURE', 'Backup Failure'), ('SECURITY_ALERT', 'Security Alert'), ('PERFORMANCE', 'Performance Issue'), ('DISK_SPACE', 'Disk Space'), ('DATABASE_ERROR', 'Database Error'), ('API_ERROR', 'API Error')], help_text='Type of alert', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], help_text='Alert severity level', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('SUPPRESSED', 'Suppressed')], default='ACTIVE', help_text='Current alert status', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the alert was acknowledged', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the alert was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the alert was resolved', null=True)),
                ('source_component', models.CharField(blank=True, help_text='System component that generated this alert', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional alert metadata', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email notification was sent')),
                ('sms_sent', models.BooleanField(default=False, help_text='Whether SMS notification was sent')),
                ('push_sent', models.BooleanField(default=False, help_text='Whether push notification was sent')),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(blank=True, help_text='User affected by this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_received', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
                ('health_check', models.ForeignKey(blank=True, help_text='Related health check if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.systemhealth')),
            ],
            options={
                'verbose_name': 'Alert Notification',
                'verbose_name_plural': 'Alert Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'created_at'], name='monitoring__alert_t_430fe4_idx'), models.Index(fields=['severity', 'status'], name='monitoring__severit_bda211_idx'), models.Index(fields=['status', 'created_at'], name='monitoring__status_661eb9_idx'), models.Index(fields=['affected_user', 'status'], name='monitoring__affecte_203d38_idx')],
            },
        ),
    ]
