# Generated by Django 6.0.4 on 2026-04-14 18:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificação de Alerta', 'verbose_name_plural': 'Notificações de Alerta'},
        ),
        migrations.AlterModelOptions(
            name='systemhealth',
            options={'ordering': ['-check_timestamp'], 'verbose_name': 'Verificação de Saúde', 'verbose_name_plural': 'Verificações de Saúde'},
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Quando o alerta foi reconhecido', null=True),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que reconheceu o alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='affected_user',
            field=models.ForeignKey(blank=True, help_text='Usuário afetado por este alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='alert_type',
            field=models.CharField(choices=[('SYSTEM_HEALTH', 'Saúde do Sistema'), ('BACKUP_FAILURE', 'Falha de Backup'), ('SECURITY_ALERT', 'Alerta de Segurança'), ('PERFORMANCE', 'Problema de Desempenho'), ('DISK_SPACE', 'Espaço em Disco'), ('DATABASE_ERROR', 'Erro no Banco de Dados'), ('API_ERROR', 'Erro de API')], help_text='Tipo de alerta', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Se a notificação por e-mail foi enviada'),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='health_check',
            field=models.ForeignKey(blank=True, help_text='Verificação de saúde relacionada, se aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.systemhealth'),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='message',
            field=models.TextField(help_text='Mensagem detalhada do alerta'),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadados adicionais do alerta', null=True),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='push_sent',
            field=models.BooleanField(default=False, help_text='Se a notificação push foi enviada'),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notas sobre como o alerta foi resolvido', null=True),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Quando o alerta foi resolvido', null=True),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que resolveu o alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], help_text='Nível de severidade do alerta', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='sms_sent',
            field=models.BooleanField(default=False, help_text='Se a notificação por SMS foi enviada'),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='source_component',
            field=models.CharField(blank=True, help_text='Componente do sistema que gerou este alerta', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('ACKNOWLEDGED', 'Reconhecido'), ('RESOLVED', 'Resolvido'), ('SUPPRESSED', 'Suprimido')], default='ACTIVE', help_text='Status atual do alerta', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='title',
            field=models.CharField(help_text='Título breve do alerta', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='active_connections',
            field=models.IntegerField(blank=True, help_text='Número de conexões ativas', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='additional_data',
            field=models.JSONField(blank=True, help_text='Métricas adicionais e metadados', null=True),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='check_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Quando esta verificação de saúde foi realizada'),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='component',
            field=models.CharField(choices=[('DATABASE', 'Banco de Dados'), ('REDIS', 'Cache Redis'), ('API', 'Serviços de API'), ('CELERY', 'Tarefas em Segundo Plano'), ('DISK', 'Armazenamento em Disco'), ('MEMORY', 'Uso de Memória'), ('CPU', 'Uso de CPU'), ('EXTERNAL_API', 'APIs Externas')], help_text='Componente do sistema sendo monitorado', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='cpu_usage',
            field=models.FloatField(blank=True, help_text='Percentual de uso de CPU', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='disk_usage',
            field=models.FloatField(blank=True, help_text='Percentual de uso de disco', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='error_count',
            field=models.IntegerField(default=0, help_text='Número de erros neste intervalo de verificação', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='error_message',
            field=models.TextField(blank=True, help_text='Última mensagem de erro, se houver', null=True),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='memory_usage',
            field=models.FloatField(blank=True, help_text='Percentual de uso de memória', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='queue_size',
            field=models.IntegerField(blank=True, help_text='Tamanho da fila de tarefas em segundo plano', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Tempo de resposta em milissegundos', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='status',
            field=models.CharField(choices=[('HEALTHY', 'Saudável'), ('WARNING', 'Aviso'), ('CRITICAL', 'Crítico'), ('DOWN', 'Inativo')], help_text='Status de saúde atual', max_length=20),
        ),
    ]
