# Generated by Django 6.0.4 on 2026-04-13 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental Backup'), ('DIFFERENTIAL', 'Differential Backup'), ('MANUAL', 'Manual Backup'), ('EMERGENCY', 'Emergency Backup')], help_text='Type of backup operation', max_length=20)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('CORRUPTED', 'Corrupted')], default='STARTED', help_text='Current backup status', max_length=20)),
                ('filename', models.CharField(help_text='Backup file name', max_length=255)),
                ('file_path', models.CharField(help_text='Full path to backup file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Backup file size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum of backup file for integrity verification', max_length=64, null=True)),
                ('started_at', models.DateTimeField(help_text='When backup operation started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When backup operation completed', null=True)),
                ('duration', models.DurationField(blank=True, help_text='Total backup duration', null=True)),
                ('database_name', models.CharField(default='default', help_text='Database name that was backed up', max_length=100)),
                ('tables_included', models.JSONField(blank=True, help_text='List of tables included in backup', null=True)),
                ('compression_used', models.BooleanField(default=True, help_text='Whether compression was used')),
                ('encryption_used', models.BooleanField(default=False, help_text='Whether encryption was used')),
                ('is_automated', models.BooleanField(default=False, help_text='Whether this was an automated backup')),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed', null=True)),
                ('error_details', models.JSONField(blank=True, help_text='Detailed error information', null=True)),
                ('retention_days', models.IntegerField(default=30, help_text='How many days to retain this backup')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this backup expires and can be deleted', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether backup has been archived to long-term storage')),
                ('archive_location', models.CharField(blank=True, help_text='Location of archived backup', max_length=500, null=True)),
                ('last_verified', models.DateTimeField(blank=True, help_text='When backup integrity was last verified', null=True)),
                ('verification_result', models.BooleanField(blank=True, help_text='Result of last integrity verification', null=True)),
                ('restore_count', models.IntegerField(default=0, help_text='Number of times this backup has been used for restore')),
                ('metadata', models.JSONField(blank=True, help_text='Additional backup metadata and configuration', null=True)),
                ('notes', models.TextField(blank=True, help_text='Administrative notes about this backup', null=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated the backup (null for automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['backup_type', 'started_at'], name='core_backup_backup__f4f1a1_idx'), models.Index(fields=['status', 'started_at'], name='core_backup_status_4be1c0_idx'), models.Index(fields=['database_name', 'started_at'], name='core_backup_databas_3f04f6_idx'), models.Index(fields=['is_automated', 'started_at'], name='core_backup_is_auto_517b50_idx'), models.Index(fields=['expires_at'], name='core_backup_expires_4f7875_idx')],
            },
        ),
    ]
