# Generated by Django 6.0.4 on 2026-04-12 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('auto', 'System Preference')], default='light', help_text='Visual theme preference for the interface', max_length=10)),
                ('density', models.CharField(choices=[('compact', 'Compact (High density)'), ('comfortable', 'Comfortable (Default)'), ('spacious', 'Spacious (Low density)')], default='comfortable', help_text='Interface density/spacing preference', max_length=15)),
                ('quick_actions', models.JSONField(blank=True, default=list, help_text='JSON array of quick action button configurations')),
                ('sidebar_collapsed', models.BooleanField(default=False, help_text='Whether the navigation sidebar is collapsed by default')),
                ('show_breadcrumbs', models.BooleanField(default=True, help_text='Whether to display breadcrumb navigation')),
                ('high_contrast', models.BooleanField(default=False, help_text='Enable high contrast mode for better accessibility')),
                ('reduce_motion', models.BooleanField(default=False, help_text='Reduce animations and motion effects')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When these preferences were first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When these preferences were last modified')),
                ('user', models.OneToOneField(help_text='User account associated with these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
