# Generated by Django 6.0.4 on 2026-04-14 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backuprecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuprecord',
            options={'ordering': ['-started_at'], 'verbose_name': 'Registro de Backup', 'verbose_name_plural': 'Registros de Backup'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Preferências do Usuário', 'verbose_name_plural': 'Preferências do Usuário'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-login_time'], 'verbose_name': 'Sessão de Usuário', 'verbose_name_plural': 'Sessões de Usuários'},
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Quando estas preferências foram criadas pela primeira vez'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='density',
            field=models.CharField(choices=[('compact', 'Compacto (Alta densidade)'), ('comfortable', 'Confortável (Padrão)'), ('spacious', 'Espaçoso (Baixa densidade)')], default='comfortable', help_text='Preferência de densidade/espaçamento da interface', max_length=15),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Ativar modo de alto contraste para melhor acessibilidade'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='quick_actions',
            field=models.JSONField(blank=True, default=list, help_text='Array JSON com configurações dos botões de ação rápida'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='reduce_motion',
            field=models.BooleanField(default=False, help_text='Reduzir animações e efeitos de movimento'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='show_breadcrumbs',
            field=models.BooleanField(default=True, help_text='Se deve exibir a navegação em trilha de migalhas'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='sidebar_collapsed',
            field=models.BooleanField(default=False, help_text='Se a barra lateral de navegação está recolhida por padrão'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Tema Claro'), ('dark', 'Tema Escuro'), ('auto', 'Preferência do Sistema')], default='light', help_text='Preferência de tema visual para a interface', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Quando estas preferências foram modificadas pela última vez'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(help_text='Conta do usuário associada a estas preferências', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
