# Generated by Django 6.0.4 on 2026-04-18 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_backuprecord_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50, verbose_name='Módulo')),
                ('resource', models.CharField(max_length=50, verbose_name='Recurso')),
                ('action', models.CharField(max_length=50, verbose_name='Ação')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Permissão')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_system', models.BooleanField(default=False, verbose_name='Permissão do Sistema')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='Requer Confirmação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['module', 'resource', 'action'],
                'unique_together': {('module', 'resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome do Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_system', models.BooleanField(default=False, verbose_name='Grupo do Sistema')),
                ('max_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de Usuários')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.usergroup', verbose_name='Grupo Pai')),
            ],
            options={
                'verbose_name': 'Grupo de Usuários',
                'verbose_name_plural': 'Grupos de Usuários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant_user', 'Conceder Permissão a Usuário'), ('revoke_user', 'Revogar Permissão de Usuário'), ('grant_group', 'Conceder Permissão a Grupo'), ('revoke_group', 'Revogar Permissão de Grupo'), ('add_to_group', 'Adicionar ao Grupo'), ('remove_from_group', 'Remover do Grupo'), ('create_group', 'Criar Grupo'), ('update_group', 'Atualizar Grupo'), ('delete_group', 'Excluir Grupo'), ('create_permission', 'Criar Permissão'), ('update_permission', 'Atualizar Permissão'), ('delete_permission', 'Excluir Permissão')], max_length=20, verbose_name='Ação')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes da Ação')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Justificativa')),
                ('result', models.CharField(choices=[('success', 'Sucesso'), ('failure', 'Falha'), ('partial', 'Parcial')], default='success', max_length=20, verbose_name='Resultado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Chave da Sessão')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que executou')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.permission', verbose_name='Permissão')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alvo')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to='core.usergroup', verbose_name='Grupo alvo')),
            ],
            options={
                'verbose_name': 'Log de Auditoria de Permissões',
                'verbose_name_plural': 'Logs de Auditoria de Permissões',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='core_permis_actor_i_6c670e_idx'), models.Index(fields=['target_user', '-created_at'], name='core_permis_target__d105e1_idx'), models.Index(fields=['action', '-created_at'], name='core_permis_action_8ee256_idx'), models.Index(fields=['created_at'], name='core_permis_created_c31c6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Negar')], default='allow', max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('inherit_to_children', models.BooleanField(default=True, verbose_name='Herdar para Subgrupos')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Justificativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_group_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='core.permission', verbose_name='Permissão')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='core.usergroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Permissão de Grupo',
                'verbose_name_plural': 'Permissões de Grupos',
                'ordering': ['group__name', 'permission__module'],
                'unique_together': {('group', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Grupo Primário')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.usergroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Associação ao Grupo',
                'verbose_name_plural': 'Associações aos Grupos',
                'ordering': ['-is_primary', 'group__name'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Negar')], default='allow', max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Justificativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.permission', verbose_name='Permissão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_new', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Usuário',
                'verbose_name_plural': 'Permissões de Usuários',
                'ordering': ['user__username', 'permission__module'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
