# Generated by Django 6.0.4 on 2026-04-18 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_hierarchical_permission_system"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracao",
            options={
                "ordering": ["categoria", "chave"],
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="result",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="session_key",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="target_group",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="joined_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Entrou no Grupo em"
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="removed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Removido do Grupo em"
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Removido por",
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Membro"),
                    ("admin", "Administrador"),
                    ("viewer", "Visualizador"),
                    ("editor", "Editor"),
                ],
                default="member",
                max_length=20,
                verbose_name="Papel no Grupo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_locked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Conta Bloqueada em"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tentativas de Login Falharam"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Atividade"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=False, verbose_name="MFA Habilitado"),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Senha Alterada em"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number_verified",
            field=models.BooleanField(
                default=False, verbose_name="Telefone Verificado"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="security_questions_set",
            field=models.BooleanField(
                default=False, verbose_name="Perguntas de Segurança Definidas"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Segredo TOTP"
            ),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="delegation_reason",
            field=models.TextField(blank=True, verbose_name="Motivo da Delegação"),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="delegation_scope_restrictions",
            field=models.JSONField(
                blank=True,
                help_text="Limitações de escopo para permissões delegadas",
                null=True,
                verbose_name="Restrições de Escopo da Delegação",
            ),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="delegation_source_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegated_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Delegou",
            ),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expira em"),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="granted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Concedido em"
            ),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="is_delegated",
            field=models.BooleanField(
                default=False,
                help_text="Indica se esta permissão foi delegada por outro usuário",
                verbose_name="É Delegada",
            ),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="is_granted",
            field=models.BooleanField(default=True, verbose_name="Concedida"),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Revogado em"
            ),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revogado por",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="descricao",
            field=models.TextField(blank=True, default="Configura????o padr??o"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("number", "Número"),
                    ("boolean", "Verdadeiro/Falso"),
                    ("json", "JSON"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permissionauditlog",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="permissionauditlog",
            name="actor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="permissionauditlog",
            name="details",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="permissionauditlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo para identificação da chave",
                        max_length=100,
                        verbose_name="Nome da Chave",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do uso da chave",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="Primeiros 8 caracteres da chave para identificação",
                        max_length=8,
                        verbose_name="Prefixo da Chave",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash da chave completa",
                        max_length=64,
                        unique=True,
                        verbose_name="Hash da Chave",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de expiração da chave",
                        null=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "scopes",
                    models.TextField(
                        blank=True,
                        help_text="Padrões de endpoints separados por vírgula (ex: GET:/api/users/*, POST:/api/orders/*)",
                        verbose_name="Escopos de Acesso",
                    ),
                ),
                (
                    "rate_limit_per_hour",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número máximo de requisições por hora (deixe vazio para ilimitado)",
                        null=True,
                        verbose_name="Limite de Requisições por Hora",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Contador de Uso"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Uso"
                    ),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Último IP utilizado"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chave de API",
                "verbose_name_plural": "Chaves de API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255, verbose_name="Endpoint")),
                ("method", models.CharField(max_length=10, verbose_name="Método HTTP")),
                (
                    "status_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Código de Status"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Endereço IP"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Timestamp da Requisição"
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tempo de Resposta (ms)"
                    ),
                ),
                (
                    "request_size_bytes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tamanho da Requisição (bytes)",
                    ),
                ),
                (
                    "response_size_bytes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tamanho da Resposta (bytes)",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="core.apikey",
                        verbose_name="Chave de API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Uso de API Key",
                "verbose_name_plural": "Logs de Uso de API Keys",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="Nome de Usuário"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Endereço IP"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("was_successful", models.BooleanField(verbose_name="Sucesso")),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Motivo da Falha"
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("password", "Senha"),
                            ("api_key", "Chave API"),
                            ("jwt", "Token JWT"),
                            ("token", "Token DRF"),
                        ],
                        default="password",
                        max_length=20,
                        verbose_name="Método de Autenticação",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Chave da Sessão"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativa de Login",
                "verbose_name_plural": "Tentativas de Login",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hash do código de backup",
                        max_length=64,
                        verbose_name="Hash do Código",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Código Utilizado"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Usado em"
                    ),
                ),
                (
                    "used_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Usado do IP"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Backup MFA",
                "verbose_name_plural": "Códigos de Backup MFA",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionApprovalRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Razão pela qual a permissão é necessária",
                        verbose_name="Justificativa",
                    ),
                ),
                (
                    "requested_duration_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Duração Solicitada (horas)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("denied", "Negado"),
                            ("expired", "Expirado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "request_expires_at",
                    models.DateTimeField(
                        help_text="Data limite para aprovação da solicitação",
                        verbose_name="Solicitação Expira em",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado em"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="core.permission",
                        verbose_name="Permissão",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Alvo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Aprovação de Permissão",
                "verbose_name_plural": "Solicitações de Aprovação de Permissões",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="userpermission",
            name="approval_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_permissions",
                to="core.permissionapprovalrequest",
                verbose_name="Solicitação de Aprovação",
            ),
        ),
        migrations.CreateModel(
            name="PermissionApprovalTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("denied", "Negado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decision",
                    models.CharField(blank=True, max_length=20, verbose_name="Decisão"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comentários")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decidido em"
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_tasks",
                        to="core.permissionapprovalrequest",
                        verbose_name="Solicitação de Aprovação",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa de Aprovação",
                "verbose_name_plural": "Tarefas de Aprovação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["key_hash"], name="core_apikey_key_has_967bbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["user", "is_active"], name="core_apikey_user_id_ea969f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["expires_at"], name="core_apikey_expires_1844aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikeyusagelog",
            index=models.Index(
                fields=["api_key", "timestamp"], name="core_apikey_api_key_89b46a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikeyusagelog",
            index=models.Index(
                fields=["timestamp"], name="core_apikey_timesta_5d40a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikeyusagelog",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="core_apikey_ip_addr_347521_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="core_logina_ip_addr_311365_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["username", "created_at"], name="core_logina_usernam_06627e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["was_successful", "created_at"],
                name="core_logina_was_suc_a59657_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mfabackupcode",
            index=models.Index(
                fields=["user", "is_used"], name="core_mfabac_user_id_3efed0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfabackupcode",
            index=models.Index(
                fields=["code_hash"], name="core_mfabac_code_ha_015eeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionapprovalrequest",
            index=models.Index(
                fields=["requester", "status", "-created_at"],
                name="core_permis_request_46e7dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionapprovalrequest",
            index=models.Index(
                fields=["target_user", "status", "-created_at"],
                name="core_permis_target__e5f9b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionapprovalrequest",
            index=models.Index(
                fields=["permission", "status"], name="core_permis_permiss_d822db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionapprovalrequest",
            index=models.Index(
                fields=["status", "request_expires_at"],
                name="core_permis_status_9b2158_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permissionapprovaltask",
            unique_together={("approval_request", "approver")},
        ),
    ]
