# Generated by Django 6.0.4 on 2026-04-19 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_configuracao_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
