# Generated by Django 6.0.4 on 2026-04-13 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('fiscal', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotafiscaleletronica',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produtovariacao'),
        ),
        migrations.AddField(
            model_name='logeventosfiscais',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.loja'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='sales.venda'),
        ),
        migrations.AddField(
            model_name='logeventosfiscais',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_eventos', to='fiscal.notafiscal'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscal'),
        ),
        migrations.AddField(
            model_name='notafiscaleletronica',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.cliente'),
        ),
        migrations.AddField(
            model_name='notafiscaleletronica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='notafiscaleletronica',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.loja'),
        ),
        migrations.AddField(
            model_name='notafiscaleletronica',
            name='venda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfe', to='sales.venda'),
        ),
        migrations.AddField(
            model_name='itemnotafiscaleletronica',
            name='nfe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscaleletronica'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaofiscal',
            unique_together={('empresa', 'loja')},
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('loja', 'tipo_nota', 'serie', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='itemnotafiscal',
            unique_together={('nota_fiscal', 'numero_item')},
        ),
    ]
