# Generated by Django 6.0.4 on 2026-04-14 18:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tintometry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Impressora')),
                ('printer_type', models.CharField(choices=[('thermal', 'Térmica'), ('inkjet', 'Jato de Tinta'), ('laser', 'Laser'), ('label', 'Etiquetadora')], max_length=20, verbose_name='Tipo')),
                ('system_name', models.CharField(help_text='Nome da impressora no sistema operacional', max_length=200, verbose_name='Nome no Sistema')),
                ('max_width_mm', models.PositiveIntegerField(default=100, verbose_name='Largura Máxima (mm)')),
                ('max_height_mm', models.PositiveIntegerField(default=150, verbose_name='Altura Máxima (mm)')),
                ('dpi', models.PositiveIntegerField(default=300, verbose_name='DPI')),
                ('supports_color', models.BooleanField(default=True, verbose_name='Suporta Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('driver_config', models.JSONField(blank=True, default=dict, verbose_name='Configurações do Driver')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Impressora',
                'verbose_name_plural': 'Configurações de Impressoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabelPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID do Trabalho')),
                ('output_type', models.CharField(choices=[('pdf', 'PDF'), ('print', 'Impressão Direta'), ('preview', 'Preview')], default='pdf', max_length=20, verbose_name='Tipo de Saída')),
                ('copies_count', models.PositiveIntegerField(default=1, verbose_name='Número de Cópias')),
                ('paper_size', models.CharField(default='a4', max_length=20, verbose_name='Tamanho do Papel')),
                ('print_quality', models.CharField(default='medium', max_length=20, verbose_name='Qualidade')),
                ('color_mode', models.CharField(default='color', max_length=20, verbose_name='Modo de Cor')),
                ('print_config', models.JSONField(blank=True, default=dict, verbose_name='Configurações de Impressão')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progresso (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('output_file_path', models.CharField(blank=True, max_length=500, verbose_name='Caminho do Arquivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels_print_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('misturas', models.ManyToManyField(related_name='labels_print_jobs', to='tintometry.misturatinta', verbose_name='Misturas')),
            ],
            options={
                'verbose_name': 'Trabalho de Impressão',
                'verbose_name_plural': 'Trabalhos de Impressão',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabelPrintQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Agendado para')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Máximo de Tentativas')),
                ('worker_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Worker')),
                ('last_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Última Tentativa')),
                ('print_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labels.labelprintjob', verbose_name='Trabalho de Impressão')),
            ],
            options={
                'verbose_name': 'Item da Fila de Impressão',
                'verbose_name_plural': 'Fila de Impressão',
                'ordering': ['priority', 'scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('standard', 'Padrão'), ('compact', 'Compacto'), ('premium', 'Premium'), ('custom', 'Personalizado')], default='standard', max_length=20, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('draft', 'Rascunho')], default='active', max_length=20, verbose_name='Status')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('width', models.PositiveIntegerField(default=100, verbose_name='Largura (mm)')),
                ('height', models.PositiveIntegerField(default=150, verbose_name='Altura (mm)')),
                ('margin', models.PositiveIntegerField(default=5, verbose_name='Margem (mm)')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor de Fundo')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Cor do Texto')),
                ('accent_color', models.CharField(default='#2563EB', max_length=7, verbose_name='Cor de Destaque')),
                ('font_family', models.CharField(default='Arial', max_length=50, verbose_name='Família da Fonte')),
                ('font_size_base', models.PositiveIntegerField(default=12, verbose_name='Tamanho Base da Fonte')),
                ('include_qr_code', models.BooleanField(default=True, verbose_name='Incluir QR Code')),
                ('include_barcode', models.BooleanField(default=True, verbose_name='Incluir Código de Barras')),
                ('include_logo', models.BooleanField(default=True, verbose_name='Incluir Logo')),
                ('include_formula', models.BooleanField(default=True, verbose_name='Incluir Lista de Pigmentos')),
                ('include_customer', models.BooleanField(default=True, verbose_name='Incluir Dados do Cliente')),
                ('include_cost', models.BooleanField(default=False, verbose_name='Incluir Informações de Custo')),
                ('layout_config', models.JSONField(blank=True, default=dict, verbose_name='Configuração de Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels_created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Etiqueta',
                'verbose_name_plural': 'Templates de Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labelprintjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.labeltemplate', verbose_name='Template Usado'),
        ),
    ]
