# Generated by Django 6.0.4 on 2026-04-13 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lojas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuarioloja',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='usuarioloja',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.loja'),
        ),
        migrations.AddField(
            model_name='usuarioloja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='loja',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioloja',
            unique_together={('usuario', 'loja')},
        ),
    ]
