# Generated by Django 6.0.4 on 2026-04-14 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_lote_validade_entrada'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidovenda',
            name='fator_conversao_aplicado',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Fator de conversão usado no momento da venda', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itempedidovenda',
            name='quantidade_base',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade convertida para unidade base do produto', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itempedidovenda',
            name='unidade_venda',
            field=models.ForeignKey(blank=True, help_text='Unidade em que a quantidade foi solicitada (lata, litro, ml, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='inventory.unidademedida'),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_chave_acesso',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_protocolo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_requer_retry_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_situacao',
            field=models.CharField(choices=[('NAO_APLICAVEL', 'Não Aplicável'), ('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('ERRO_TECNICO', 'Erro Técnico'), ('AGUARDANDO_RETRY', 'Aguardando Retry Manual')], default='NAO_APLICAVEL', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_tentativas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_tipo_emissao',
            field=models.CharField(blank=True, choices=[('AUTOMATICA_B2B', 'Automática B2B'), ('MANUAL_B2C', 'Manual B2C'), ('NAO_EMITIR', 'Não Emitir')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_ultima_tentativa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
