# Generated by Django 6.0.4 on 2026-04-15 18:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('sales', '0002_nfe_automation_and_multiunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='desconto_aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='desconto_aprovador',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou o desconto via PIN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descontos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='desconto_motivo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='tem_devolucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Nulo para vendas balcão anônimo (BR-001)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.cliente'),
        ),
        migrations.CreateModel(
            name='DescontoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_desconto', models.CharField(choices=[('ITEM', 'Por Item'), ('TOTAL', 'No Total')], max_length=10)),
                ('valor_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_depois', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('aprovado_com_pin', models.BooleanField(default=False)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descontos_aprovados_log', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_desconto', to='sales.itempedidovenda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_desconto', to='sales.pedidovenda')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descontos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Desconto',
                'verbose_name_plural': 'Logs de Desconto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forma', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_DEBITO', 'Cartão Débito'), ('CARTAO_CREDITO', 'Cartão Crédito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('CHEQUE', 'Cheque'), ('CREDIARIO', 'Crediário'), ('FIADO', 'Fiado')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, help_text='Valor entregue pelo cliente (somente DINHEIRO)', max_digits=12, null=True)),
                ('troco', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=300, null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='sales.venda')),
            ],
            options={
                'verbose_name': 'Pagamento de Venda',
                'verbose_name_plural': 'Pagamentos de Venda',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recebivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_saldo', models.DecimalField(decimal_places=2, help_text='Computed from valor_original - valor_pago; always >= 0', max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('situacao', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('PAGO', 'Pago'), ('PARCIAL', 'Parcialmente Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_com_override', models.BooleanField(default=False, help_text='True quando limite de crédito foi excedido e aprovado por gerência')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=500, null=True)),
                ('aprovador_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_credito', to=settings.AUTH_USER_MODEL)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebiveis_cancelados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='sales.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.loja')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='sales.venda')),
            ],
            options={
                'verbose_name': 'Recebível',
                'verbose_name_plural': 'Recebíveis',
                'ordering': ['data_vencimento'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_saldo__gte', 0)), name='recebivel_saldo_nao_negativo')],
            },
        ),
    ]
