# Generated by Django 6.0.4 on 2026-04-15 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('sales', '0003_sales_pdv_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedidovenda',
            index=models.Index(fields=['loja', 'situacao', 'created_at'], name='pedidovenda_loja_sit_idx'),
        ),
        migrations.AddIndex(
            model_name='recebivel',
            index=models.Index(fields=['cliente', 'situacao'], name='recebivel_cliente_sit_idx'),
        ),
        migrations.AddIndex(
            model_name='recebivel',
            index=models.Index(fields=['loja', 'data_vencimento', 'situacao'], name='recebivel_loja_venc_sit_idx'),
        ),
    ]
